name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: ğŸ“¦ Instalar DependÃªncias
        run: npm install

      - name: ğŸ§ª Subir Sistema e Executar Testes UI
        run: npx ci:test:ui

      - name: ğŸ“ Salvar VÃ­deos (se houver)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-videos
          path: cypress/videos

      - name: ğŸ“ Salvar Screenshots (se falhar)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots
          path: cypress/screenshots

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: ğŸ“¦ Instalar DependÃªncias
        run: npm install

      - name: ğŸ§ª Subir Sistema e Executar Testes API
        run: npx ci:test:api

      - name: ğŸ“ Salvar VÃ­deos (se houver)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-videos
          path: cypress/videos

      - name: ğŸ“ Salvar Screenshots (se falhar)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-screenshots
          path: cypress/screenshots